USE jugos_ventas;

SELECT * FROM tabla_de_vendedores;

SELECT * FROM facturas;

SELECT * FROM tabla_de_vendedores A 
INNER JOIN facturas B 
ON A.MATRICULA = B.MATRICULA;

SELECT *
FROM tabla_de_vendedores AS A
INNER JOIN facturas AS B
    ON A.MATRICULA = B.MATRICULA;
    
SELECT A.NOMBRE, B.MATRICULA,
COUNT(*)
FROM tabla_de_vendedores AS A
INNER JOIN facturas AS B
    ON A.MATRICULA = B.MATRICULA
GROUP BY A.NOMBRE, B.MATRICULA;

SELECT A.NOMBRE, B.MATRICULA,
    COUNT(*) AS TOTAL_FACTURAS
FROM 
    tabla_de_vendedores AS A
INNER JOIN 
    facturas AS B
    ON A.MATRICULA = B.MATRICULA
GROUP BY A.NOMBRE, B.MATRICULA;

SELECT DNI, COUNT(*) FROM facturas
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY DNI
HAVING COUNT(*) > 2000;

SELECT X.ENVASE, X. PRECIO_MAXIMO FROM
vw_envases_grandes X 
WHERE PRECIO_MAXIMO >=10;

SELECT A.NOMBRE_DEL_PRODUCTO, A.ENVASE, A.PRECIO_DE_LISTA, 
B.PRECIO_MAXIMO FROM tabla_de_productos A
INNER JOIN
vw_envases_grandes B
ON A.ENVASE = B.ENVASE;