USE jugos_ventas;
SELECT * FROM facturas; 

SELECT * FROM items_facturas;

SELECT F.DNI, F.FECHA_VENTA, IFa.CANTIDAD
FROM FACTURAS F
INNER JOIN 
items_facturas IFa 
ON F.NUMERO = IFa.NUMERO;

SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO, IFa.CANTIDAD
FROM FACTURAS F
INNER JOIN 
items_facturas IFa 
ON F.NUMERO = IFa.NUMERO;

/*Cantidad de ventas por Mes */
SELECT F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA
FROM FACTURAS F
INNER JOIN 
items_facturas IFa 
ON F.NUMERO = IFa.NUMERO
GROUP BY F.DNI, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y');

/*LIMITE DE VENTAS POR CLIENTES (VOLUMEN EN DECILITROS)*/
SELECT * FROM tabla_de_clientes TC;

SELECT DNI, NOMBRE, VOLUMEN_DE_COMPRA
FROM tabla_de_clientes TC;

SELECT F.DNI, TC.NOMBRE,  DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
FROM FACTURAS F
INNER JOIN 
items_facturas IFa 
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y');

SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA
FROM (
SELECT F.DNI, TC.NOMBRE,  DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
FROM FACTURAS F
INNER JOIN 
items_facturas IFa 
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y')
)A;

/* Añadiendo CASE*/
SELECT A.DNI, A.NOMBRE, A.MES_AÑO, 
A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
CASE
	WHEN A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA <= 0 THEN 'Venta valida'
    ELSE 'Invalida'
END AS ESTATUS_VENTA    
FROM (
SELECT F.DNI, TC.NOMBRE,  DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO, 
SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, MAX(VOLUMEN_DE_COMPRA)/10 AS CANTIDAD_MAXIMA
FROM FACTURAS F
INNER JOIN 
items_facturas IFa 
ON F.NUMERO = IFa.NUMERO
INNER JOIN
tabla_de_clientes TC
ON TC.DNI = F.DNI
GROUP BY F.DNI, TC.NOMBRE, DATE_FORMAT(F.FECHA_VENTA, '%m - %Y')
)A;

/*MISMA QUIERY SOLO CORRECCION VISUAL*/
SELECT 
    A.DNI, 
    A.NOMBRE, 
    A.MES_AÑO, 
    A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA AS DIFERENCIA,
    CASE
        WHEN A.CANTIDAD_VENDIDA - A.CANTIDAD_MAXIMA <= 0 THEN 'Venta válida'
        ELSE 'Inválida'
    END AS ESTATUS_VENTA
FROM (
    SELECT 
        F.DNI, 
        TC.NOMBRE,  
        DATE_FORMAT(F.FECHA_VENTA, '%m - %Y') AS MES_AÑO, 
        SUM(IFa.CANTIDAD) AS CANTIDAD_VENDIDA, 
        MAX(VOLUMEN_DE_COMPRA) / 10 AS CANTIDAD_MAXIMA
    FROM 
        FACTURAS F
    INNER JOIN 
        items_facturas IFa 
        ON F.NUMERO = IFa.NUMERO
    INNER JOIN
        tabla_de_clientes TC
        ON TC.DNI = F.DNI
    GROUP BY 
        F.DNI, 
        TC.NOMBRE, 
        DATE_FORMAT(F.FECHA_VENTA, '%m - %Y')
) AS A;